<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Grounding Monitoring System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="assets/css/tabler-icons.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
</head>

<body>
    <header class="header-ui">
        <!-- Bagian Tengah: Judul -->
        <div class="header-center">
            <div class="header-title">
                GROUNDING CHECKER MONITORING
            </div>
        </div>

        <!-- Bagian Kanan -->
        <div class="header-right">
            <div class="dropdown-container">
                <button class="nav-btn" onclick="toggleDropdown()" id="menuButton">
                    <i class="ti ti-menu-2"></i>
                    <span>MENU</span>
                    <i class="ti ti-chevron-down" style="font-size: 0.8em;"></i>
                </button>
                <div id="nav-dropdown" class="dropdown-menu">
                    <a href="index.php" class="dropdown-item" target="_top">
                        <i class="ti ti-dashboard" style="margin-right:5px"></i> Dashboard Utama
                    </a>
                    <div style="border-top: 1px solid #fce7f3; margin: 5px 0;"></div>
                    <span style="display:block; padding: 5px 16px; font-size: 0.8em; color:#831843;">System Active</span>
                </div>
            </div>

            <div class="header-clock">
                <div id="time-display" class="clock-time">--:--:--</div>
                <div id="date-display" class="clock-date">-- -- ----</div>
            </div>
        </div>
    </header>

    <div class="grid" id="monitor-grid">
        <!-- Cards generated by JS -->
    </div>

    <audio id="alarmSound" src="assets/alarm.wav" allow="autoplay; fullscreen" preload="auto" loop></audio>

    <footer>
        <div class="legend">
            <div class="legend-item"><span class="legend-box ok"></span><span>Normal</span></div>
            <div class="legend-item"><span class="legend-box warning"></span><span>Warning</span></div>
            <div class="legend-item"><span class="legend-box disconnected"></span><span>Fault</span></div>
            <div class="legend-item"><span class="legend-box unknown"></span><span>Unknown</span></div>
        </div>
        <div class="note">Data updates every 2s. Alarm active on fault.</div>
    </footer>

    <script src="assets/js/app.js"></script>

</body>

</html>
