<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Grounding Monitoring System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="assets/css/tabler-icons.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
</head>

<body>
    <header class="header-ui">
        <div class="header-left">
            <h1 class="header-title">GROUNDING CHECKER MONITORING</h1>
            <p class="header-subtitle" id="header-subtitle-text">&nbsp;</p>
        </div>
        <div class="header-right">
            <nav class="nav-menu">
                <div class="dropdown-container">
                    <button class="dropdown-toggle" onclick="toggleDropdown()" id="menuButton" title="Menu">
                        <i class="ti ti-menu-2" style="font-size: 1.2em;"></i>
                        <span>MENU</span>
                    </button>
                    <div id="nav-dropdown" class="dropdown-menu">
                        <a href="index.php" class="dropdown-item" target="_top">
                            Environment Monitoring
                        </a>
                    </div>
                </div>
            </nav>
            <button id="audio-toggle" class="sound-btn" title="Enable/Disable Sound">
                <div id="audio-icon-container" class="flex items-center justify-center">
                    <svg class="sound-icon muted-icon" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z" />
                        <path stroke-linecap="round" stroke-linejoin="round" d="M17 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2" />
                    </svg>
                    <svg class="sound-icon unmuted-icon" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z" />
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15.536 8.464a5 5 0 010 7.072m2.828-9.9a9 9 0 010 12.728" />
                    </svg>
                </div>
            </button>
            <div class="header-clock">
                <div id="time-display" class="clock-time">--:--:--</div>
                <div id="date-display" class="clock-date">-- -- ----</div>
            </div>
        </div>
    </header>

    <main>
        <div class="grid" id="monitor-grid">
            <!-- Cards generated by JS -->
        </div>
    </main>

    <footer>
        <div class="footer-left">
            <div class="legend" style="flex-direction: row; align-items: center; gap: 20px;">
                <div class="legend-item">
                    <span class="legend-box ok"></span>
                    <span style="font-weight: 600; font-size: 1.1em;">Ground path is <strong>normal</strong>.</span>
                </div>
                <div class="legend-item">
                    <span class="legend-box disconnected"></span>
                    <span style="font-weight: 600; font-size: 1.1em;">Ground path has a <strong>fault.</strong></span>
                </div>
                <div class="legend-item">
                    <span class="legend-box unknown"></span>
                    <span style="font-weight: 600; font-size: 1.1em;">Anomaly Sensor.</span>
                </div>
            </div>
        </div>
        <div class="info-note" style="max-width: 800px;">
            Status updates automatically every 2 seconds. Alarm and blinking animation are active only during a fault.
        </div>
    </footer>

    <audio id="alarmSound" src="assets/alarm.wav" preload="auto"></audio>
    <script src="assets/js/app.js"></script>

</body>

</html>
